### PR TITLE
allow figsize pass to audio_spectrogram_image

### PR DESCRIPTION
**Pull request by lyramakesmusic**
`spectrogram_image` allows passing an optional figsize, but that arg is not propagated to the `audio_spectrogram_image` wrapper. This edit lets you control that directly, for example if you want wider spectrograms: `wandb.Image(audio_spectrogram_image(fakes, figsize=(15, 4)))`

### CODE REVIEW

**Comment by drscotthawley** [comment]
Oooo, thanks for the fix, Lyra!   But the checks failed because we need the change to go in the .ipynb file, not the .py file (as those are always overwritten by `nbdev`)  
Guess I need to clarify that in the [Contributing](https://github.com/drscotthawley/aeiou?tab=readme-ov-file#contributing) section of the README. 
If you want to make the change yourself and re-submit, I'll gladly accept it so you get the PR credit! 
Or if you'd rather I just make the same change myself in the .ipynb flie, I can do that. 
Let me know what you want to do.

**Comment by lyramakesmusic** [comment]
just to clarify- I do have to run `nbdev`, I can't just edit the `ipynb` and push? I've been editing via github web, not a local copy

**Comment by drscotthawley** [comment]
Yea you can't just edit on the web, the CI will fail due to timestamp errors, and the docs won't build correctly either.  

As per [Contributing](https://github.com/drscotthawley/aeiou?tab=readme-ov-file#contributing):
> 5.  After editing notebooks, run `nbdev_prepare`

You need to run `nbdev_prepare` or at *least* `nbdev_export`, otherwise the .ipynb and .py files won't be sync'd and the Github Actions CI will throw an error and fail.  But `_prepare` also builds the documentation.

**Comment by drscotthawley** [comment]
It might be easier if I just make the change and push it ,since I'm used to this stuff. (I could do it, and add a note in the Comment that I'm pasting in your change.)

But I'd still be happy to wait for you to do it if you want to.

**Comment by lyramakesmusic** [comment]
works for me! I can try out the build tools later if I run into something again

**Comment by drscotthawley** [comment]
Ok, working on it!  
Having trouble with `nbdev_prepare` myself right now, crashing. :-/ .  Might have to apply the change on Linux instead of my Mac....

**Comment by drscotthawley** [comment]
Closing this PR, as now implemented via Commit https://github.com/drscotthawley/aeiou/commit/448a75462b11380ed98400b64dbef56155a5c22b! 🥳

**Pull request closed without merging**
